version: 0.2
environment_variables:
    plaintext:
        S3_BUCKET: "arn:aws:s3:::codepipeline-us-east-1-583843697584"

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - aws s3 cp dist/pointclub s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
